### ISSUE TITLE
Playerclasses flags

### ISSUE THREAD

**Issue by Rushaway** [srcdslab/sm-plugin-zombiereloaded#20]
Using playerclasses configs with sourcemod flags are ignoring root flags.
It will always try to find the exact match without knowing root flags have all flags.

Exemple of configs used:
`sm_flags "o" `
- `o` is a custom flag, the plugin will not find the match with root flag. So it will not give an access to the playerclasse.

**Comment by maxime1907** [comment]
nice catch
