### ISSUE TITLE
Error in compile

### ISSUE THREAD

**Issue by ShyperOne** [srcdslab/sm-plugin-zombiereloaded#3]
// zr\translation.inc(89) : error 017: undefined symbol "MC_AddWhiteSpace"

**Comment by maxime1907** [comment]
You need to use our multicolors:
- https://github.com/srcdslab/sm-plugin-multicolors

But good point, i will add a if defined

**Comment by maxime1907** [comment]
@Rushaway

I was just thinking back of the code that i wrote for multicolors and you can remove `MC_AddWhiteSpace` to implement it directly in `CFormatColor`

https://github.com/srcdslab/sm-plugin-MultiColors/blob/master/addons/sourcemod/scripting/include/multicolors.inc#L296

**Comment by maxime1907** [comment]
fixed in https://github.com/srcdslab/sm-plugin-zombiereloaded/commit/5a91faf66e69843c4e5aa0f16aed754c7fed7457
